### ISSUE TITLE
Tags for 'maintained by deepset' 

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#125]
Hey @carlosgauci - we would like to have a minor update to the integrations page. Could we tag the ones that the author name is 'deepset' with a tag that says 'maintained by deepset'? 

1. Would it be possible to add these tags to the cards and into the pages themselves?
2. Can we then also add a filter to the page where we show all of them by default but allow to filter to 'maintained by deepset'? - I'm not entirely sure what kind of filter would make sense for this? Any suggestions? 

Eventually we may add some more tags but let's start with these. 
I've made some tags and draft image of what we would like to get to here. 

<img width="1147" alt="image" src="https://github.com/deepset-ai/haystack-home/assets/15802862/de73a229-4006-456e-9f05-9e97858a4ec6">

![Maintained by deepset (3)](https://github.com/deepset-ai/haystack-home/assets/15802862/4a47fa83-2bb7-4cb8-b4cb-42cd19710854)

**Comment by carlosgauci** [comment]
Hey @TuanaCelik, sure we can do it, since it's one filter for now maybe we could just add a checkbox for "maintained by deepset"?
![maintained](https://github.com/deepset-ai/haystack-home/assets/53526597/a03ffa26-853f-4a07-9395-c3e9a17585f1)

Or else we can make another select (all maintainers, maintained by deepset, maintained by community), and rename the default option for the current select filter to "All Types" instead of "All Integrations". LMK what you think.
