### ISSUE TITLE
Meta description/name/image

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#158]
Meta descriptions etc work fine on social sites like twitter but fail e.g. here: https://www.heymeta.com/url/haystack.deepset.ai/blog/what-is-an-llm

I think it's because the title, descriptions, images etc are added to opengraph elements but not meta?

**Comment by carlosgauci** [comment]
> 

Hey Tuana, the image wasn't working because the site wasn't reading the relative urls (same problem we had with twitter.) Mad a PR https://www.heymeta.com/url/haystack-home-git-meta-deepset-overnice.vercel.app/blog/what-is-an-llm  and turned them into absolute URLs which will fix it:
https://www.heymeta.com/url/haystack-home-git-meta-deepset-overnice.vercel.app/blog/what-is-an-llm

Also you're right we were missing the description tag, though it was being inferred from the social tags, still a good idea to add it :)
